package handler

import (
	"context"

	"github.com/AGubenskiy/metrics/internal/audit"
	models "github.com/AGubenskiy/metrics/internal/model"
)

// MetricsService describes application operations used by HTTP handlers.
type MetricsService interface {
	UpdateGauge(ctx context.Context, name string, value float64) error
	UpdateCounter(ctx context.Context, name string, value int64) error
	UpdateMetrics(ctx context.Context, metrics []models.Metrics) error
	GetGauge(ctx context.Context, name string) (float64, bool)
	GetCounter(ctx context.Context, name string) (int64, bool)
	GetAll(ctx context.Context) (map[string]float64, map[string]int64)
}

// Pinger checks that the backing database connection is healthy.
type Pinger interface {
	PingContext(ctx context.Context) error
}

// AuditPublisher publishes audit events generated by handlers.
type AuditPublisher interface {
	Notify(ctx context.Context, event audit.Event) error
}
