package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	resetMarker       = "generate:reset"
	generatedFileName = "reset.gen.go"
	generatedHeader   = "// Code generated by cmd/reset. DO NOT EDIT.\n"
)

type typeKey struct {
	pkgPath string
	name    string
}

type resetTarget struct {
	name  string
	named *types.Named
}

type packagePlan struct {
	dir     string
	pkg     *packages.Package
	targets []resetTarget
}

type importTracker struct {
	currentName string
	currentPath string
	aliases     map[string]string
}

type generator struct {
	pkg     *packages.Package
	marked  map[typeKey]struct{}
	imports *importTracker
	counter int
}

type codeWriter struct {
	builder strings.Builder
}

func main() {
	root, err := findModuleRoot()
	if err != nil {
		log.Fatal(err)
	}

	if err := run(root); err != nil {
		log.Fatal(err)
	}
}

func run(root string) error {
	pkgs, err := loadPackages(root)
	if err != nil {
		return err
	}

	plans, marked, err := collectPlans(pkgs)
	if err != nil {
		return err
	}

	sort.Slice(plans, func(i, j int) bool {
		return plans[i].pkg.PkgPath < plans[j].pkg.PkgPath
	})

	for _, plan := range plans {
		if len(plan.targets) == 0 {
			if err := removeGeneratedFileIfPresent(plan.dir); err != nil {
				return err
			}
			continue
		}

		if err := writeGeneratedFile(plan, marked); err != nil {
			return err
		}
	}

	return nil
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err = os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found in current directory tree")
		}
		dir = parent
	}
}

func loadPackages(root string) ([]*packages.Package, error) {
	overlay, err := generatedOverlay(root)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
		Dir:     root,
		Fset:    fset,
		Overlay: overlay,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, err
	}

	var problems []string
	packages.Visit(pkgs, nil, func(pkg *packages.Package) {
		for _, pkgErr := range pkg.Errors {
			problems = append(problems, pkgErr.Error())
		}
	})

	if len(problems) > 0 {
		sort.Strings(problems)
		return nil, errors.New(strings.Join(problems, "\n"))
	}

	return pkgs, nil
}

func generatedOverlay(root string) (map[string][]byte, error) {
	overlay := make(map[string][]byte)

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if d.IsDir() {
			switch d.Name() {
			case ".git", ".idea", "vendor":
				return filepath.SkipDir
			}
			return nil
		}

		if d.Name() != generatedFileName {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		file, err := parser.ParseFile(token.NewFileSet(), path, data, parser.PackageClauseOnly)
		if err != nil {
			return err
		}

		overlay[path] = []byte("package " + file.Name.Name + "\n")
		return nil
	})
	if err != nil {
		return nil, err
	}

	return overlay, nil
}

func collectPlans(pkgs []*packages.Package) ([]packagePlan, map[typeKey]struct{}, error) {
	plans := make([]packagePlan, 0, len(pkgs))
	marked := make(map[typeKey]struct{})

	for _, pkg := range pkgs {
		dir := packageDir(pkg)
		if dir == "" {
			continue
		}

		manualResets := manualResetTypes(pkg)
		targets, err := markedTargets(pkg)
		if err != nil {
			return nil, nil, err
		}

		for _, target := range targets {
			key := keyForNamed(target.named)
			if _, exists := manualResets[key]; exists {
				return nil, nil, fmt.Errorf("%s.%s already declares Reset", pkg.PkgPath, target.name)
			}
			marked[key] = struct{}{}
		}

		sort.Slice(targets, func(i, j int) bool {
			return targets[i].name < targets[j].name
		})

		plans = append(plans, packagePlan{
			dir:     dir,
			pkg:     pkg,
			targets: targets,
		})
	}

	return plans, marked, nil
}

func packageDir(pkg *packages.Package) string {
	switch {
	case len(pkg.GoFiles) > 0:
		return filepath.Dir(pkg.GoFiles[0])
	case len(pkg.CompiledGoFiles) > 0:
		return filepath.Dir(pkg.CompiledGoFiles[0])
	default:
		return ""
	}
}

func manualResetTypes(pkg *packages.Package) map[typeKey]struct{} {
	manual := make(map[typeKey]struct{})

	for _, file := range pkg.Syntax {
		if filepath.Base(pkg.Fset.Position(file.Pos()).Filename) == generatedFileName {
			continue
		}

		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || fn.Name.Name != "Reset" {
				continue
			}

			obj, ok := pkg.TypesInfo.Defs[fn.Name].(*types.Func)
			if !ok {
				continue
			}

			sig, ok := obj.Type().(*types.Signature)
			if !ok || sig.Recv() == nil {
				continue
			}

			named := baseNamed(sig.Recv().Type())
			if named == nil {
				continue
			}

			manual[keyForNamed(named)] = struct{}{}
		}
	}

	return manual
}

func markedTargets(pkg *packages.Package) ([]resetTarget, error) {
	var targets []resetTarget
	seen := make(map[typeKey]struct{})

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || !hasResetMarker(genDecl.Doc, typeSpec.Doc) {
					continue
				}

				obj, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					return nil, fmt.Errorf("unable to resolve type %s in %s", typeSpec.Name.Name, pkg.PkgPath)
				}

				named, ok := types.Unalias(obj.Type()).(*types.Named)
				if !ok {
					return nil, fmt.Errorf("%s.%s is not a defined type", pkg.PkgPath, typeSpec.Name.Name)
				}

				if _, ok := named.Underlying().(*types.Struct); !ok {
					return nil, fmt.Errorf("%s.%s is marked for reset but is not a struct", pkg.PkgPath, typeSpec.Name.Name)
				}

				key := keyForNamed(named)
				if _, exists := seen[key]; exists {
					continue
				}

				seen[key] = struct{}{}
				targets = append(targets, resetTarget{
					name:  typeSpec.Name.Name,
					named: named,
				})
			}
		}
	}

	return targets, nil
}

func hasResetMarker(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}

		for _, comment := range group.List {
			text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
			text = strings.TrimSpace(strings.TrimPrefix(text, "/*"))
			text = strings.TrimSpace(strings.TrimSuffix(text, "*/"))
			if text == resetMarker {
				return true
			}
		}
	}

	return false
}

func writeGeneratedFile(plan packagePlan, marked map[typeKey]struct{}) error {
	gen := &generator{
		pkg:    plan.pkg,
		marked: marked,
		imports: &importTracker{
			currentName: plan.pkg.Name,
			currentPath: plan.pkg.PkgPath,
			aliases:     make(map[string]string),
		},
	}

	writer := &codeWriter{}
	writer.line(0, strings.TrimSpace(generatedHeader))
	writer.line(0, "")
	writer.line(0, "package "+plan.pkg.Name)

	methods := make([]string, 0, len(plan.targets))
	for _, target := range plan.targets {
		methods = append(methods, gen.renderMethod(target))
	}

	importBlock := gen.renderImports()
	if importBlock != "" {
		writer.line(0, "")
		writer.line(0, importBlock)
	}

	for _, method := range methods {
		writer.line(0, "")
		writer.line(0, method)
	}

	formatted, err := format.Source([]byte(writer.String()))
	if err != nil {
		return fmt.Errorf("format %s: %w", plan.pkg.PkgPath, err)
	}

	path := filepath.Join(plan.dir, generatedFileName)
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}

	return nil
}

func removeGeneratedFileIfPresent(dir string) error {
	path := filepath.Join(dir, generatedFileName)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	if !bytes.HasPrefix(data, []byte(generatedHeader)) {
		return nil
	}

	return os.Remove(path)
}

func (g *generator) renderMethod(target resetTarget) string {
	writer := &codeWriter{}
	receiverName := "r"

	writer.line(0, fmt.Sprintf("func (%s %s) Reset() {", receiverName, g.receiverType(target)))
	writer.line(1, fmt.Sprintf("if %s == nil {", receiverName))
	writer.line(2, "return")
	writer.line(1, "}")

	stack := make(map[typeKey]int)
	g.emitStructReset(writer, 1, receiverName, target.named, target.named.Underlying().(*types.Struct), stack)
	writer.line(0, "}")

	return strings.TrimSpace(writer.String())
}

func (g *generator) receiverType(target resetTarget) string {
	params := target.named.TypeParams()
	if params == nil || params.Len() == 0 {
		return "*" + target.name
	}

	names := make([]string, 0, params.Len())
	for i := 0; i < params.Len(); i++ {
		names = append(names, params.At(i).Obj().Name())
	}

	return fmt.Sprintf("*%s[%s]", target.name, strings.Join(names, ", "))
}

func (g *generator) renderImports() string {
	if len(g.imports.aliases) == 0 {
		return ""
	}

	paths := make([]string, 0, len(g.imports.aliases))
	for path := range g.imports.aliases {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var builder strings.Builder
	builder.WriteString("import (\n")
	for _, path := range paths {
		alias := g.imports.aliases[path]
		defaultName := filepath.Base(path)
		builder.WriteString("\t")
		if alias != defaultName {
			builder.WriteString(alias)
			builder.WriteString(" ")
		}
		builder.WriteString(fmt.Sprintf("%q\n", path))
	}
	builder.WriteString(")")

	return builder.String()
}

func (g *generator) emitReset(writer *codeWriter, indent int, expr string, typ types.Type, stack map[typeKey]int) {
	typ = types.Unalias(typ)

	switch underlying := typ.Underlying().(type) {
	case *types.Pointer:
		g.emitPointerReset(writer, indent, expr, typ, underlying, stack)
	case *types.Interface:
		if g.canCallReset(typ) {
			writer.line(indent, fmt.Sprintf("if %s != nil {", expr))
			writer.line(indent+1, expr+".Reset()")
			writer.line(indent, "}")
			return
		}
		g.emitZeroAssign(writer, indent, expr, typ)
	case *types.TypeParam:
		g.emitZeroAssign(writer, indent, expr, typ)
	default:
		if g.canCallReset(typ) {
			writer.line(indent, expr+".Reset()")
			return
		}
		g.emitByUnderlyingType(writer, indent, expr, typ, typ.Underlying(), stack)
	}
}

func (g *generator) emitByUnderlyingType(
	writer *codeWriter,
	indent int,
	expr string,
	typ types.Type,
	underlying types.Type,
	stack map[typeKey]int,
) {
	switch underlying := underlying.(type) {
	case *types.Basic:
		g.emitZeroAssign(writer, indent, expr, typ)
	case *types.Slice:
		writer.line(indent, fmt.Sprintf("%s = %s[:0]", expr, expr))
	case *types.Map:
		writer.line(indent, fmt.Sprintf("clear(%s)", expr))
	case *types.Array:
		g.emitArrayReset(writer, indent, expr, underlying, stack)
	case *types.Struct:
		g.emitStructReset(writer, indent, expr, typ, underlying, stack)
	case *types.Signature, *types.Chan:
		g.emitZeroAssign(writer, indent, expr, typ)
	default:
		g.emitZeroAssign(writer, indent, expr, typ)
	}
}

func (g *generator) emitPointerReset(writer *codeWriter, indent int, expr string, typ types.Type, ptr *types.Pointer, stack map[typeKey]int) {
	writer.line(indent, fmt.Sprintf("if %s != nil {", expr))

	if g.canCallReset(typ) {
		writer.line(indent+1, expr+".Reset()")
		writer.line(indent, "}")
		return
	}

	g.emitReset(writer, indent+1, fmt.Sprintf("(*%s)", expr), ptr.Elem(), stack)
	writer.line(indent, "}")
}

func (g *generator) emitArrayReset(writer *codeWriter, indent int, expr string, array *types.Array, stack map[typeKey]int) {
	indexName := g.nextName("i")
	writer.line(indent, fmt.Sprintf("for %s := range %s {", indexName, expr))
	g.emitReset(writer, indent+1, fmt.Sprintf("%s[%s]", expr, indexName), array.Elem(), stack)
	writer.line(indent, "}")
}

func (g *generator) emitStructReset(writer *codeWriter, indent int, expr string, typ types.Type, st *types.Struct, stack map[typeKey]int) {
	key, foreign := g.structResetKey(typ)
	if foreign {
		g.emitZeroAssign(writer, indent, expr, typ)
		return
	}

	if key.name != "" {
		if stack[key] > 0 {
			g.emitZeroAssign(writer, indent, expr, typ)
			return
		}
		stack[key]++
		defer func() {
			stack[key]--
		}()
	}

	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		if field.Name() == "_" {
			continue
		}
		g.emitReset(writer, indent, expr+"."+field.Name(), field.Type(), stack)
	}
}

func (g *generator) emitZeroAssign(writer *codeWriter, indent int, expr string, typ types.Type) {
	if literal, ok := zeroLiteral(typ); ok {
		writer.line(indent, fmt.Sprintf("%s = %s", expr, literal))
		return
	}

	typeName := g.imports.typeString(typ)
	zeroName := g.nextName("zero")
	writer.line(indent, fmt.Sprintf("var %s %s", zeroName, typeName))
	writer.line(indent, fmt.Sprintf("%s = %s", expr, zeroName))
}

func (g *generator) canCallReset(typ types.Type) bool {
	if named := baseNamed(typ); named != nil {
		if _, exists := g.marked[keyForNamed(named)]; exists {
			return true
		}
	}

	method, _, _ := types.LookupFieldOrMethod(typ, true, g.pkg.Types, "Reset")
	return method != nil
}

func (g *generator) structResetKey(typ types.Type) (typeKey, bool) {
	named, ok := types.Unalias(typ).(*types.Named)
	if !ok {
		return typeKey{}, false
	}

	key := keyForNamed(named)
	if key.pkgPath == "" || key.pkgPath == g.pkg.PkgPath {
		return key, false
	}

	return key, true
}

func (g *generator) nextName(prefix string) string {
	g.counter++
	return fmt.Sprintf("%s%d", prefix, g.counter)
}

func (t *importTracker) typeString(typ types.Type) string {
	return types.TypeString(types.Unalias(typ), t.qualifier)
}

func (t *importTracker) qualifier(pkg *types.Package) string {
	if pkg == nil || pkg.Path() == "" || pkg.Path() == t.currentPath {
		return ""
	}

	if alias, ok := t.aliases[pkg.Path()]; ok {
		return alias
	}

	base := pkg.Name()
	if base == "" {
		base = filepath.Base(pkg.Path())
	}

	alias := base
	for t.conflicts(alias) {
		alias = fmt.Sprintf("%s%d", base, len(t.aliases)+1)
	}

	t.aliases[pkg.Path()] = alias
	return alias
}

func (t *importTracker) conflicts(alias string) bool {
	if alias == t.currentName {
		return true
	}

	for _, existing := range t.aliases {
		if existing == alias {
			return true
		}
	}

	return false
}

func zeroLiteral(typ types.Type) (string, bool) {
	typ = types.Unalias(typ)

	switch underlying := typ.Underlying().(type) {
	case *types.Basic:
		info := underlying.Info()
		switch {
		case info&types.IsBoolean != 0:
			return "false", true
		case info&types.IsString != 0:
			return `""`, true
		case info&(types.IsInteger|types.IsFloat|types.IsComplex) != 0:
			return "0", true
		case underlying.Kind() == types.UnsafePointer:
			return "nil", true
		}
	case *types.Pointer, *types.Interface, *types.Slice, *types.Map, *types.Signature, *types.Chan:
		return "nil", true
	}

	return "", false
}

func baseNamed(typ types.Type) *types.Named {
	typ = types.Unalias(typ)

	switch typed := typ.(type) {
	case *types.Named:
		return typed
	case *types.Pointer:
		return baseNamed(typed.Elem())
	default:
		return nil
	}
}

func keyForNamed(named *types.Named) typeKey {
	obj := named.Obj()
	if obj == nil {
		return typeKey{}
	}

	if pkg := obj.Pkg(); pkg != nil {
		return typeKey{pkgPath: pkg.Path(), name: obj.Name()}
	}

	return typeKey{name: obj.Name()}
}

func (w *codeWriter) line(indent int, text string) {
	for i := 0; i < indent; i++ {
		w.builder.WriteByte('\t')
	}
	w.builder.WriteString(text)
	w.builder.WriteByte('\n')
}

func (w *codeWriter) String() string {
	return w.builder.String()
}
